version: '3.7'
services:
  web:
    build: .
    ports:
      - "80:8080"
    env_file:
      - mysql-config.env
      
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - mysqldbvolume:/var/lib/mysql
    env_file:
      - mysql-config.env

volumes:
  mysqldbvolume:
    driver: local